// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mensagem_ia_gerente_dados.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "mensagem_ia_gerente_dados.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* PacoteVelocidades_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PacoteVelocidades_reflection_ = NULL;
const ::google::protobuf::Descriptor* PacoteIAGerenteDados_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PacoteIAGerenteDados_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_mensagem_5fia_5fgerente_5fdados_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_mensagem_5fia_5fgerente_5fdados_2eproto() {
  protobuf_AddDesc_mensagem_5fia_5fgerente_5fdados_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "mensagem_ia_gerente_dados.proto");
  GOOGLE_CHECK(file != NULL);
  PacoteVelocidades_descriptor_ = file->message_type(0);
  static const int PacoteVelocidades_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteVelocidades, id_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteVelocidades, vx_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteVelocidades, vy_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteVelocidades, vtheta_),
  };
  PacoteVelocidades_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PacoteVelocidades_descriptor_,
      PacoteVelocidades::default_instance_,
      PacoteVelocidades_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteVelocidades, _has_bits_[0]),
      -1,
      -1,
      sizeof(PacoteVelocidades),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteVelocidades, _internal_metadata_),
      -1);
  PacoteIAGerenteDados_descriptor_ = file->message_type(1);
  static const int PacoteIAGerenteDados_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteIAGerenteDados, numframe_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteIAGerenteDados, velocidades_),
  };
  PacoteIAGerenteDados_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PacoteIAGerenteDados_descriptor_,
      PacoteIAGerenteDados::default_instance_,
      PacoteIAGerenteDados_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteIAGerenteDados, _has_bits_[0]),
      -1,
      -1,
      sizeof(PacoteIAGerenteDados),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteIAGerenteDados, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_mensagem_5fia_5fgerente_5fdados_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PacoteVelocidades_descriptor_, &PacoteVelocidades::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PacoteIAGerenteDados_descriptor_, &PacoteIAGerenteDados::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_mensagem_5fia_5fgerente_5fdados_2eproto() {
  delete PacoteVelocidades::default_instance_;
  delete PacoteVelocidades_reflection_;
  delete PacoteIAGerenteDados::default_instance_;
  delete PacoteIAGerenteDados_reflection_;
}

void protobuf_AddDesc_mensagem_5fia_5fgerente_5fdados_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_mensagem_5fia_5fgerente_5fdados_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\037mensagem_ia_gerente_dados.proto\"G\n\021Pac"
    "oteVelocidades\022\n\n\002id\030\001 \002(\r\022\n\n\002vx\030\002 \002(\002\022\n"
    "\n\002vy\030\003 \002(\002\022\016\n\006vtheta\030\004 \002(\002\"Q\n\024PacoteIAGe"
    "renteDados\022\020\n\010numFrame\030\001 \002(\r\022\'\n\013velocida"
    "des\030\002 \003(\0132\022.PacoteVelocidades", 189);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "mensagem_ia_gerente_dados.proto", &protobuf_RegisterTypes);
  PacoteVelocidades::default_instance_ = new PacoteVelocidades();
  PacoteIAGerenteDados::default_instance_ = new PacoteIAGerenteDados();
  PacoteVelocidades::default_instance_->InitAsDefaultInstance();
  PacoteIAGerenteDados::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_mensagem_5fia_5fgerente_5fdados_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_mensagem_5fia_5fgerente_5fdados_2eproto {
  StaticDescriptorInitializer_mensagem_5fia_5fgerente_5fdados_2eproto() {
    protobuf_AddDesc_mensagem_5fia_5fgerente_5fdados_2eproto();
  }
} static_descriptor_initializer_mensagem_5fia_5fgerente_5fdados_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PacoteVelocidades::kIdFieldNumber;
const int PacoteVelocidades::kVxFieldNumber;
const int PacoteVelocidades::kVyFieldNumber;
const int PacoteVelocidades::kVthetaFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PacoteVelocidades::PacoteVelocidades()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PacoteVelocidades)
}

void PacoteVelocidades::InitAsDefaultInstance() {
}

PacoteVelocidades::PacoteVelocidades(const PacoteVelocidades& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PacoteVelocidades)
}

void PacoteVelocidades::SharedCtor() {
  _cached_size_ = 0;
  id_ = 0u;
  vx_ = 0;
  vy_ = 0;
  vtheta_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PacoteVelocidades::~PacoteVelocidades() {
  // @@protoc_insertion_point(destructor:PacoteVelocidades)
  SharedDtor();
}

void PacoteVelocidades::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PacoteVelocidades::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PacoteVelocidades::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PacoteVelocidades_descriptor_;
}

const PacoteVelocidades& PacoteVelocidades::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_mensagem_5fia_5fgerente_5fdados_2eproto();
  return *default_instance_;
}

PacoteVelocidades* PacoteVelocidades::default_instance_ = NULL;

PacoteVelocidades* PacoteVelocidades::New(::google::protobuf::Arena* arena) const {
  PacoteVelocidades* n = new PacoteVelocidades;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PacoteVelocidades::Clear() {
// @@protoc_insertion_point(message_clear_start:PacoteVelocidades)
#if defined(__clang__)
#define ZR_HELPER_(f) \
  _Pragma("clang diagnostic push") \
  _Pragma("clang diagnostic ignored \"-Winvalid-offsetof\"") \
  __builtin_offsetof(PacoteVelocidades, f) \
  _Pragma("clang diagnostic pop")
#else
#define ZR_HELPER_(f) reinterpret_cast<char*>(\
  &reinterpret_cast<PacoteVelocidades*>(16)->f)
#endif

#define ZR_(first, last) do {\
  ::memset(&first, 0,\
           ZR_HELPER_(last) - ZR_HELPER_(first) + sizeof(last));\
} while (0)

  ZR_(id_, vtheta_);

#undef ZR_HELPER_
#undef ZR_

  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool PacoteVelocidades::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PacoteVelocidades)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 id = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &id_)));
          set_has_id();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(21)) goto parse_vx;
        break;
      }

      // required float vx = 2;
      case 2: {
        if (tag == 21) {
         parse_vx:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &vx_)));
          set_has_vx();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(29)) goto parse_vy;
        break;
      }

      // required float vy = 3;
      case 3: {
        if (tag == 29) {
         parse_vy:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &vy_)));
          set_has_vy();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(37)) goto parse_vtheta;
        break;
      }

      // required float vtheta = 4;
      case 4: {
        if (tag == 37) {
         parse_vtheta:
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &vtheta_)));
          set_has_vtheta();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PacoteVelocidades)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PacoteVelocidades)
  return false;
#undef DO_
}

void PacoteVelocidades::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PacoteVelocidades)
  // required uint32 id = 1;
  if (has_id()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->id(), output);
  }

  // required float vx = 2;
  if (has_vx()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->vx(), output);
  }

  // required float vy = 3;
  if (has_vy()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->vy(), output);
  }

  // required float vtheta = 4;
  if (has_vtheta()) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->vtheta(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:PacoteVelocidades)
}

::google::protobuf::uint8* PacoteVelocidades::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PacoteVelocidades)
  // required uint32 id = 1;
  if (has_id()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->id(), target);
  }

  // required float vx = 2;
  if (has_vx()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->vx(), target);
  }

  // required float vy = 3;
  if (has_vy()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->vy(), target);
  }

  // required float vtheta = 4;
  if (has_vtheta()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->vtheta(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PacoteVelocidades)
  return target;
}

int PacoteVelocidades::RequiredFieldsByteSizeFallback() const {
// @@protoc_insertion_point(required_fields_byte_size_fallback_start:PacoteVelocidades)
  int total_size = 0;

  if (has_id()) {
    // required uint32 id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->id());
  }

  if (has_vx()) {
    // required float vx = 2;
    total_size += 1 + 4;
  }

  if (has_vy()) {
    // required float vy = 3;
    total_size += 1 + 4;
  }

  if (has_vtheta()) {
    // required float vtheta = 4;
    total_size += 1 + 4;
  }

  return total_size;
}
int PacoteVelocidades::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:PacoteVelocidades)
  int total_size = 0;

  if (((_has_bits_[0] & 0x0000000f) ^ 0x0000000f) == 0) {  // All required fields are present.
    // required uint32 id = 1;
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->id());

    // required float vx = 2;
    total_size += 1 + 4;

    // required float vy = 3;
    total_size += 1 + 4;

    // required float vtheta = 4;
    total_size += 1 + 4;

  } else {
    total_size += RequiredFieldsByteSizeFallback();
  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PacoteVelocidades::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PacoteVelocidades)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PacoteVelocidades* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PacoteVelocidades>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PacoteVelocidades)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PacoteVelocidades)
    MergeFrom(*source);
  }
}

void PacoteVelocidades::MergeFrom(const PacoteVelocidades& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PacoteVelocidades)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_id()) {
      set_id(from.id());
    }
    if (from.has_vx()) {
      set_vx(from.vx());
    }
    if (from.has_vy()) {
      set_vy(from.vy());
    }
    if (from.has_vtheta()) {
      set_vtheta(from.vtheta());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void PacoteVelocidades::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PacoteVelocidades)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PacoteVelocidades::CopyFrom(const PacoteVelocidades& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PacoteVelocidades)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PacoteVelocidades::IsInitialized() const {
  if ((_has_bits_[0] & 0x0000000f) != 0x0000000f) return false;

  return true;
}

void PacoteVelocidades::Swap(PacoteVelocidades* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PacoteVelocidades::InternalSwap(PacoteVelocidades* other) {
  std::swap(id_, other->id_);
  std::swap(vx_, other->vx_);
  std::swap(vy_, other->vy_);
  std::swap(vtheta_, other->vtheta_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PacoteVelocidades::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PacoteVelocidades_descriptor_;
  metadata.reflection = PacoteVelocidades_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PacoteVelocidades

// required uint32 id = 1;
bool PacoteVelocidades::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void PacoteVelocidades::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
void PacoteVelocidades::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
void PacoteVelocidades::clear_id() {
  id_ = 0u;
  clear_has_id();
}
 ::google::protobuf::uint32 PacoteVelocidades::id() const {
  // @@protoc_insertion_point(field_get:PacoteVelocidades.id)
  return id_;
}
 void PacoteVelocidades::set_id(::google::protobuf::uint32 value) {
  set_has_id();
  id_ = value;
  // @@protoc_insertion_point(field_set:PacoteVelocidades.id)
}

// required float vx = 2;
bool PacoteVelocidades::has_vx() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void PacoteVelocidades::set_has_vx() {
  _has_bits_[0] |= 0x00000002u;
}
void PacoteVelocidades::clear_has_vx() {
  _has_bits_[0] &= ~0x00000002u;
}
void PacoteVelocidades::clear_vx() {
  vx_ = 0;
  clear_has_vx();
}
 float PacoteVelocidades::vx() const {
  // @@protoc_insertion_point(field_get:PacoteVelocidades.vx)
  return vx_;
}
 void PacoteVelocidades::set_vx(float value) {
  set_has_vx();
  vx_ = value;
  // @@protoc_insertion_point(field_set:PacoteVelocidades.vx)
}

// required float vy = 3;
bool PacoteVelocidades::has_vy() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void PacoteVelocidades::set_has_vy() {
  _has_bits_[0] |= 0x00000004u;
}
void PacoteVelocidades::clear_has_vy() {
  _has_bits_[0] &= ~0x00000004u;
}
void PacoteVelocidades::clear_vy() {
  vy_ = 0;
  clear_has_vy();
}
 float PacoteVelocidades::vy() const {
  // @@protoc_insertion_point(field_get:PacoteVelocidades.vy)
  return vy_;
}
 void PacoteVelocidades::set_vy(float value) {
  set_has_vy();
  vy_ = value;
  // @@protoc_insertion_point(field_set:PacoteVelocidades.vy)
}

// required float vtheta = 4;
bool PacoteVelocidades::has_vtheta() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
void PacoteVelocidades::set_has_vtheta() {
  _has_bits_[0] |= 0x00000008u;
}
void PacoteVelocidades::clear_has_vtheta() {
  _has_bits_[0] &= ~0x00000008u;
}
void PacoteVelocidades::clear_vtheta() {
  vtheta_ = 0;
  clear_has_vtheta();
}
 float PacoteVelocidades::vtheta() const {
  // @@protoc_insertion_point(field_get:PacoteVelocidades.vtheta)
  return vtheta_;
}
 void PacoteVelocidades::set_vtheta(float value) {
  set_has_vtheta();
  vtheta_ = value;
  // @@protoc_insertion_point(field_set:PacoteVelocidades.vtheta)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PacoteIAGerenteDados::kNumFrameFieldNumber;
const int PacoteIAGerenteDados::kVelocidadesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PacoteIAGerenteDados::PacoteIAGerenteDados()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PacoteIAGerenteDados)
}

void PacoteIAGerenteDados::InitAsDefaultInstance() {
}

PacoteIAGerenteDados::PacoteIAGerenteDados(const PacoteIAGerenteDados& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PacoteIAGerenteDados)
}

void PacoteIAGerenteDados::SharedCtor() {
  _cached_size_ = 0;
  numframe_ = 0u;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PacoteIAGerenteDados::~PacoteIAGerenteDados() {
  // @@protoc_insertion_point(destructor:PacoteIAGerenteDados)
  SharedDtor();
}

void PacoteIAGerenteDados::SharedDtor() {
  if (this != default_instance_) {
  }
}

void PacoteIAGerenteDados::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PacoteIAGerenteDados::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PacoteIAGerenteDados_descriptor_;
}

const PacoteIAGerenteDados& PacoteIAGerenteDados::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_mensagem_5fia_5fgerente_5fdados_2eproto();
  return *default_instance_;
}

PacoteIAGerenteDados* PacoteIAGerenteDados::default_instance_ = NULL;

PacoteIAGerenteDados* PacoteIAGerenteDados::New(::google::protobuf::Arena* arena) const {
  PacoteIAGerenteDados* n = new PacoteIAGerenteDados;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PacoteIAGerenteDados::Clear() {
// @@protoc_insertion_point(message_clear_start:PacoteIAGerenteDados)
  numframe_ = 0u;
  velocidades_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool PacoteIAGerenteDados::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PacoteIAGerenteDados)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required uint32 numFrame = 1;
      case 1: {
        if (tag == 8) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::uint32, ::google::protobuf::internal::WireFormatLite::TYPE_UINT32>(
                 input, &numframe_)));
          set_has_numframe();
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_velocidades;
        break;
      }

      // repeated .PacoteVelocidades velocidades = 2;
      case 2: {
        if (tag == 18) {
         parse_velocidades:
          DO_(input->IncrementRecursionDepth());
         parse_loop_velocidades:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_velocidades()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_loop_velocidades;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PacoteIAGerenteDados)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PacoteIAGerenteDados)
  return false;
#undef DO_
}

void PacoteIAGerenteDados::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PacoteIAGerenteDados)
  // required uint32 numFrame = 1;
  if (has_numframe()) {
    ::google::protobuf::internal::WireFormatLite::WriteUInt32(1, this->numframe(), output);
  }

  // repeated .PacoteVelocidades velocidades = 2;
  for (unsigned int i = 0, n = this->velocidades_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, this->velocidades(i), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:PacoteIAGerenteDados)
}

::google::protobuf::uint8* PacoteIAGerenteDados::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PacoteIAGerenteDados)
  // required uint32 numFrame = 1;
  if (has_numframe()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteUInt32ToArray(1, this->numframe(), target);
  }

  // repeated .PacoteVelocidades velocidades = 2;
  for (unsigned int i = 0, n = this->velocidades_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, this->velocidades(i), false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PacoteIAGerenteDados)
  return target;
}

int PacoteIAGerenteDados::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:PacoteIAGerenteDados)
  int total_size = 0;

  // required uint32 numFrame = 1;
  if (has_numframe()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::UInt32Size(
        this->numframe());
  }
  // repeated .PacoteVelocidades velocidades = 2;
  total_size += 1 * this->velocidades_size();
  for (int i = 0; i < this->velocidades_size(); i++) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        this->velocidades(i));
  }

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PacoteIAGerenteDados::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PacoteIAGerenteDados)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PacoteIAGerenteDados* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PacoteIAGerenteDados>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PacoteIAGerenteDados)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PacoteIAGerenteDados)
    MergeFrom(*source);
  }
}

void PacoteIAGerenteDados::MergeFrom(const PacoteIAGerenteDados& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PacoteIAGerenteDados)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  velocidades_.MergeFrom(from.velocidades_);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_numframe()) {
      set_numframe(from.numframe());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void PacoteIAGerenteDados::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PacoteIAGerenteDados)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PacoteIAGerenteDados::CopyFrom(const PacoteIAGerenteDados& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PacoteIAGerenteDados)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PacoteIAGerenteDados::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000001) != 0x00000001) return false;

  if (!::google::protobuf::internal::AllAreInitialized(this->velocidades())) return false;
  return true;
}

void PacoteIAGerenteDados::Swap(PacoteIAGerenteDados* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PacoteIAGerenteDados::InternalSwap(PacoteIAGerenteDados* other) {
  std::swap(numframe_, other->numframe_);
  velocidades_.UnsafeArenaSwap(&other->velocidades_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PacoteIAGerenteDados::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PacoteIAGerenteDados_descriptor_;
  metadata.reflection = PacoteIAGerenteDados_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PacoteIAGerenteDados

// required uint32 numFrame = 1;
bool PacoteIAGerenteDados::has_numframe() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void PacoteIAGerenteDados::set_has_numframe() {
  _has_bits_[0] |= 0x00000001u;
}
void PacoteIAGerenteDados::clear_has_numframe() {
  _has_bits_[0] &= ~0x00000001u;
}
void PacoteIAGerenteDados::clear_numframe() {
  numframe_ = 0u;
  clear_has_numframe();
}
 ::google::protobuf::uint32 PacoteIAGerenteDados::numframe() const {
  // @@protoc_insertion_point(field_get:PacoteIAGerenteDados.numFrame)
  return numframe_;
}
 void PacoteIAGerenteDados::set_numframe(::google::protobuf::uint32 value) {
  set_has_numframe();
  numframe_ = value;
  // @@protoc_insertion_point(field_set:PacoteIAGerenteDados.numFrame)
}

// repeated .PacoteVelocidades velocidades = 2;
int PacoteIAGerenteDados::velocidades_size() const {
  return velocidades_.size();
}
void PacoteIAGerenteDados::clear_velocidades() {
  velocidades_.Clear();
}
const ::PacoteVelocidades& PacoteIAGerenteDados::velocidades(int index) const {
  // @@protoc_insertion_point(field_get:PacoteIAGerenteDados.velocidades)
  return velocidades_.Get(index);
}
::PacoteVelocidades* PacoteIAGerenteDados::mutable_velocidades(int index) {
  // @@protoc_insertion_point(field_mutable:PacoteIAGerenteDados.velocidades)
  return velocidades_.Mutable(index);
}
::PacoteVelocidades* PacoteIAGerenteDados::add_velocidades() {
  // @@protoc_insertion_point(field_add:PacoteIAGerenteDados.velocidades)
  return velocidades_.Add();
}
::google::protobuf::RepeatedPtrField< ::PacoteVelocidades >*
PacoteIAGerenteDados::mutable_velocidades() {
  // @@protoc_insertion_point(field_mutable_list:PacoteIAGerenteDados.velocidades)
  return &velocidades_;
}
const ::google::protobuf::RepeatedPtrField< ::PacoteVelocidades >&
PacoteIAGerenteDados::velocidades() const {
  // @@protoc_insertion_point(field_list:PacoteIAGerenteDados.velocidades)
  return velocidades_;
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
