// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mensagem_gerente_dados.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "mensagem_gerente_dados.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* PacoteDados_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PacoteDados_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_mensagem_5fgerente_5fdados_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_mensagem_5fgerente_5fdados_2eproto() {
  protobuf_AddDesc_mensagem_5fgerente_5fdados_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "mensagem_gerente_dados.proto");
  GOOGLE_CHECK(file != NULL);
  PacoteDados_descriptor_ = file->message_type(0);
  static const int PacoteDados_offsets_[3] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteDados, dadosvisao_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteDados, dadosestados_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteDados, dadoscontrole_),
  };
  PacoteDados_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PacoteDados_descriptor_,
      PacoteDados::default_instance_,
      PacoteDados_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteDados, _has_bits_[0]),
      -1,
      -1,
      sizeof(PacoteDados),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PacoteDados, _internal_metadata_),
      -1);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_mensagem_5fgerente_5fdados_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PacoteDados_descriptor_, &PacoteDados::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_mensagem_5fgerente_5fdados_2eproto() {
  delete PacoteDados::default_instance_;
  delete PacoteDados_reflection_;
}

void protobuf_AddDesc_mensagem_5fgerente_5fdados_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AddDesc_mensagem_5fgerente_5fdados_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::protobuf_AddDesc_messages_5frobocup_5fssl_5freferee_2eproto();
  ::protobuf_AddDesc_mensagem_5fgerente_5fvisao_2eproto();
  ::protobuf_AddDesc_mensagem_5fcontrole_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\034mensagem_gerente_dados.proto\032\"messages"
    "_robocup_ssl_referee.proto\032\034mensagem_ger"
    "ente_visao.proto\032\027mensagem_controle.prot"
    "o\"{\n\013PacoteDados\022 \n\ndadosVisao\030\001 \001(\0132\014.P"
    "acoteVisao\022\"\n\014dadosEstados\030\002 \001(\0132\014.SSL_R"
    "eferee\022&\n\rdadosControle\030\003 \001(\0132\017.PacoteCo"
    "ntrole", 246);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "mensagem_gerente_dados.proto", &protobuf_RegisterTypes);
  PacoteDados::default_instance_ = new PacoteDados();
  PacoteDados::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_mensagem_5fgerente_5fdados_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_mensagem_5fgerente_5fdados_2eproto {
  StaticDescriptorInitializer_mensagem_5fgerente_5fdados_2eproto() {
    protobuf_AddDesc_mensagem_5fgerente_5fdados_2eproto();
  }
} static_descriptor_initializer_mensagem_5fgerente_5fdados_2eproto_;

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PacoteDados::kDadosVisaoFieldNumber;
const int PacoteDados::kDadosEstadosFieldNumber;
const int PacoteDados::kDadosControleFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PacoteDados::PacoteDados()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PacoteDados)
}

void PacoteDados::InitAsDefaultInstance() {
  dadosvisao_ = const_cast< ::PacoteVisao*>(&::PacoteVisao::default_instance());
  dadosestados_ = const_cast< ::SSL_Referee*>(&::SSL_Referee::default_instance());
  dadoscontrole_ = const_cast< ::PacoteControle*>(&::PacoteControle::default_instance());
}

PacoteDados::PacoteDados(const PacoteDados& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PacoteDados)
}

void PacoteDados::SharedCtor() {
  _cached_size_ = 0;
  dadosvisao_ = NULL;
  dadosestados_ = NULL;
  dadoscontrole_ = NULL;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

PacoteDados::~PacoteDados() {
  // @@protoc_insertion_point(destructor:PacoteDados)
  SharedDtor();
}

void PacoteDados::SharedDtor() {
  if (this != default_instance_) {
    delete dadosvisao_;
    delete dadosestados_;
    delete dadoscontrole_;
  }
}

void PacoteDados::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PacoteDados::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PacoteDados_descriptor_;
}

const PacoteDados& PacoteDados::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_mensagem_5fgerente_5fdados_2eproto();
  return *default_instance_;
}

PacoteDados* PacoteDados::default_instance_ = NULL;

PacoteDados* PacoteDados::New(::google::protobuf::Arena* arena) const {
  PacoteDados* n = new PacoteDados;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PacoteDados::Clear() {
// @@protoc_insertion_point(message_clear_start:PacoteDados)
  if (_has_bits_[0 / 32] & 7u) {
    if (has_dadosvisao()) {
      if (dadosvisao_ != NULL) dadosvisao_->::PacoteVisao::Clear();
    }
    if (has_dadosestados()) {
      if (dadosestados_ != NULL) dadosestados_->::SSL_Referee::Clear();
    }
    if (has_dadoscontrole()) {
      if (dadoscontrole_ != NULL) dadoscontrole_->::PacoteControle::Clear();
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  if (_internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->Clear();
  }
}

bool PacoteDados::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PacoteDados)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .PacoteVisao dadosVisao = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_dadosvisao()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_dadosEstados;
        break;
      }

      // optional .SSL_Referee dadosEstados = 2;
      case 2: {
        if (tag == 18) {
         parse_dadosEstados:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_dadosestados()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_dadosControle;
        break;
      }

      // optional .PacoteControle dadosControle = 3;
      case 3: {
        if (tag == 26) {
         parse_dadosControle:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_dadoscontrole()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PacoteDados)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PacoteDados)
  return false;
#undef DO_
}

void PacoteDados::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PacoteDados)
  // optional .PacoteVisao dadosVisao = 1;
  if (has_dadosvisao()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *this->dadosvisao_, output);
  }

  // optional .SSL_Referee dadosEstados = 2;
  if (has_dadosestados()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->dadosestados_, output);
  }

  // optional .PacoteControle dadosControle = 3;
  if (has_dadoscontrole()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      3, *this->dadoscontrole_, output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:PacoteDados)
}

::google::protobuf::uint8* PacoteDados::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PacoteDados)
  // optional .PacoteVisao dadosVisao = 1;
  if (has_dadosvisao()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *this->dadosvisao_, false, target);
  }

  // optional .SSL_Referee dadosEstados = 2;
  if (has_dadosestados()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->dadosestados_, false, target);
  }

  // optional .PacoteControle dadosControle = 3;
  if (has_dadoscontrole()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        3, *this->dadoscontrole_, false, target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:PacoteDados)
  return target;
}

int PacoteDados::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:PacoteDados)
  int total_size = 0;

  if (_has_bits_[0 / 32] & 7u) {
    // optional .PacoteVisao dadosVisao = 1;
    if (has_dadosvisao()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->dadosvisao_);
    }

    // optional .SSL_Referee dadosEstados = 2;
    if (has_dadosestados()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->dadosestados_);
    }

    // optional .PacoteControle dadosControle = 3;
    if (has_dadoscontrole()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *this->dadoscontrole_);
    }

  }
  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PacoteDados::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PacoteDados)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  const PacoteDados* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PacoteDados>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PacoteDados)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PacoteDados)
    MergeFrom(*source);
  }
}

void PacoteDados::MergeFrom(const PacoteDados& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PacoteDados)
  if (GOOGLE_PREDICT_FALSE(&from == this)) {
    ::google::protobuf::internal::MergeFromFail(__FILE__, __LINE__);
  }
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_dadosvisao()) {
      mutable_dadosvisao()->::PacoteVisao::MergeFrom(from.dadosvisao());
    }
    if (from.has_dadosestados()) {
      mutable_dadosestados()->::SSL_Referee::MergeFrom(from.dadosestados());
    }
    if (from.has_dadoscontrole()) {
      mutable_dadoscontrole()->::PacoteControle::MergeFrom(from.dadoscontrole());
    }
  }
  if (from._internal_metadata_.have_unknown_fields()) {
    mutable_unknown_fields()->MergeFrom(from.unknown_fields());
  }
}

void PacoteDados::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PacoteDados)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PacoteDados::CopyFrom(const PacoteDados& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PacoteDados)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PacoteDados::IsInitialized() const {

  if (has_dadosvisao()) {
    if (!this->dadosvisao_->IsInitialized()) return false;
  }
  if (has_dadosestados()) {
    if (!this->dadosestados_->IsInitialized()) return false;
  }
  if (has_dadoscontrole()) {
    if (!this->dadoscontrole_->IsInitialized()) return false;
  }
  return true;
}

void PacoteDados::Swap(PacoteDados* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PacoteDados::InternalSwap(PacoteDados* other) {
  std::swap(dadosvisao_, other->dadosvisao_);
  std::swap(dadosestados_, other->dadosestados_);
  std::swap(dadoscontrole_, other->dadoscontrole_);
  std::swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PacoteDados::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PacoteDados_descriptor_;
  metadata.reflection = PacoteDados_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PacoteDados

// optional .PacoteVisao dadosVisao = 1;
bool PacoteDados::has_dadosvisao() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
void PacoteDados::set_has_dadosvisao() {
  _has_bits_[0] |= 0x00000001u;
}
void PacoteDados::clear_has_dadosvisao() {
  _has_bits_[0] &= ~0x00000001u;
}
void PacoteDados::clear_dadosvisao() {
  if (dadosvisao_ != NULL) dadosvisao_->::PacoteVisao::Clear();
  clear_has_dadosvisao();
}
const ::PacoteVisao& PacoteDados::dadosvisao() const {
  // @@protoc_insertion_point(field_get:PacoteDados.dadosVisao)
  return dadosvisao_ != NULL ? *dadosvisao_ : *default_instance_->dadosvisao_;
}
::PacoteVisao* PacoteDados::mutable_dadosvisao() {
  set_has_dadosvisao();
  if (dadosvisao_ == NULL) {
    dadosvisao_ = new ::PacoteVisao;
  }
  // @@protoc_insertion_point(field_mutable:PacoteDados.dadosVisao)
  return dadosvisao_;
}
::PacoteVisao* PacoteDados::release_dadosvisao() {
  // @@protoc_insertion_point(field_release:PacoteDados.dadosVisao)
  clear_has_dadosvisao();
  ::PacoteVisao* temp = dadosvisao_;
  dadosvisao_ = NULL;
  return temp;
}
void PacoteDados::set_allocated_dadosvisao(::PacoteVisao* dadosvisao) {
  delete dadosvisao_;
  dadosvisao_ = dadosvisao;
  if (dadosvisao) {
    set_has_dadosvisao();
  } else {
    clear_has_dadosvisao();
  }
  // @@protoc_insertion_point(field_set_allocated:PacoteDados.dadosVisao)
}

// optional .SSL_Referee dadosEstados = 2;
bool PacoteDados::has_dadosestados() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
void PacoteDados::set_has_dadosestados() {
  _has_bits_[0] |= 0x00000002u;
}
void PacoteDados::clear_has_dadosestados() {
  _has_bits_[0] &= ~0x00000002u;
}
void PacoteDados::clear_dadosestados() {
  if (dadosestados_ != NULL) dadosestados_->::SSL_Referee::Clear();
  clear_has_dadosestados();
}
const ::SSL_Referee& PacoteDados::dadosestados() const {
  // @@protoc_insertion_point(field_get:PacoteDados.dadosEstados)
  return dadosestados_ != NULL ? *dadosestados_ : *default_instance_->dadosestados_;
}
::SSL_Referee* PacoteDados::mutable_dadosestados() {
  set_has_dadosestados();
  if (dadosestados_ == NULL) {
    dadosestados_ = new ::SSL_Referee;
  }
  // @@protoc_insertion_point(field_mutable:PacoteDados.dadosEstados)
  return dadosestados_;
}
::SSL_Referee* PacoteDados::release_dadosestados() {
  // @@protoc_insertion_point(field_release:PacoteDados.dadosEstados)
  clear_has_dadosestados();
  ::SSL_Referee* temp = dadosestados_;
  dadosestados_ = NULL;
  return temp;
}
void PacoteDados::set_allocated_dadosestados(::SSL_Referee* dadosestados) {
  delete dadosestados_;
  dadosestados_ = dadosestados;
  if (dadosestados) {
    set_has_dadosestados();
  } else {
    clear_has_dadosestados();
  }
  // @@protoc_insertion_point(field_set_allocated:PacoteDados.dadosEstados)
}

// optional .PacoteControle dadosControle = 3;
bool PacoteDados::has_dadoscontrole() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
void PacoteDados::set_has_dadoscontrole() {
  _has_bits_[0] |= 0x00000004u;
}
void PacoteDados::clear_has_dadoscontrole() {
  _has_bits_[0] &= ~0x00000004u;
}
void PacoteDados::clear_dadoscontrole() {
  if (dadoscontrole_ != NULL) dadoscontrole_->::PacoteControle::Clear();
  clear_has_dadoscontrole();
}
const ::PacoteControle& PacoteDados::dadoscontrole() const {
  // @@protoc_insertion_point(field_get:PacoteDados.dadosControle)
  return dadoscontrole_ != NULL ? *dadoscontrole_ : *default_instance_->dadoscontrole_;
}
::PacoteControle* PacoteDados::mutable_dadoscontrole() {
  set_has_dadoscontrole();
  if (dadoscontrole_ == NULL) {
    dadoscontrole_ = new ::PacoteControle;
  }
  // @@protoc_insertion_point(field_mutable:PacoteDados.dadosControle)
  return dadoscontrole_;
}
::PacoteControle* PacoteDados::release_dadoscontrole() {
  // @@protoc_insertion_point(field_release:PacoteDados.dadosControle)
  clear_has_dadoscontrole();
  ::PacoteControle* temp = dadoscontrole_;
  dadoscontrole_ = NULL;
  return temp;
}
void PacoteDados::set_allocated_dadoscontrole(::PacoteControle* dadoscontrole) {
  delete dadoscontrole_;
  dadoscontrole_ = dadoscontrole;
  if (dadoscontrole) {
    set_has_dadoscontrole();
  } else {
    clear_has_dadoscontrole();
  }
  // @@protoc_insertion_point(field_set_allocated:PacoteDados.dadosControle)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
